[Main]
# Режим вычислений: LUFS (взвешенная громкость) или RMS
LoudnessMode = LUFS
# вывод времени выполнения yes | no
show_time = no
# расширенный лог
verbose = no
# Включить сравнение треков по схожести имён (yes/no)
delta_comparison = yes
# Включить overlay графики Loudness Flow при 2 файлах (yes/no)
overlay_flow = yes
# Высота всех графиков в пикселях
plot_height_px = 920

[LoudnessDensity]
# Максимальное отображаемое время (ось Y), сек
y_max_sec = 30
# Левая граница оси X (LUFS)
x_min_db = -40
# Правая граница оси X (LUFS)
x_max_db = 0
# Количество столбиков
bins = 160
# Цвет столбиков
HLineColor = #10AA10
# Цвет столбика при превышении y_max_sec
HOverColor = #30FF20
# Цвет меток осей (черный для белого фона)
HLabelColor = #003000

# Включить построение графика VolumeFlow (yes/no)
[LoudnessFlow]
Enabled = yes
# Минимальное окно (микродинамика), сек
WindowMin = 0.01
# Максимальное окно (макродинамика), сек
WindowMax = 16
# Количество расчетных точек (логарифмический шаг)
Steps = 12
# Отсекать 5% пиков и 10% тишины (EBU метод) (yes/no)
Cut5 = yes
# Максимум вертикальной шкалы, дБ
YMaxDB = 24
# Цвет ломаной линии
VLineColor = #10AA10
# Цвет меток осей (черный для белого фона)
VLabelColor = #002000